name: better_infinite_list
description: "A Better Infinite List For handling error and loading in much efficient way."
version: 0.0.22
homepage: https://github.com/NewsunBanjade/BetterInfiniteList

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
